/*
=== AVENGERS-LEVEL CHALLENGE: WAKANDA SHIELD INVASION ===

Problem Statement generated by Gemini, Coded by Amezcua.

Las hordas de Outriders de Thanos están presionando el escudo. Para evitar que el domo 
colapse, debes programar el sistema de distribución de energía táctica de Shuri.

Tu programa debe cumplir los siguientes requerimientos:

1. Estructura de Datos y Seguridad de Entrada (Filtro Anti-Fallas):
   Declarar la matriz 'float shield[3][5]'. Al capturar los datos (0.0 a 100.0%), 
   el programa debe validar la entrada. Si el operador ingresa un valor negativo o mayor 
   a 100, el sistema debe mostrar un error y REPETIR la solicitud de ese nodo específico 
   sin avanzar los índices.

2. Análisis Cardinal Complejo (Recorrido Invertido por Columnas):
   Para balancear los generadores principales, calcula y muestra el promedio de energía 
   de cada una de las 5 columnas por separado. Asocia cada columna a su sector en el reporte:
   - Columna 0: Sector Norte
   - Columna 1: Sector Sur
   - Columna 2: Sector Este
   - Columna 3: Sector Oeste
   - Columna 4: Sector Central

3. Localización de la Brecha de Invasión:
   Encuentra la coordenada exacta [Fila][Columna] que tenga el porcentaje de energía MÁS BAJO 
   de todo el domo (la Brecha). Guarda también el valor MÁXIMO absoluto de energía encontrado.

4. Protocolo de Diagnóstico de Shuri (Criterio de Desbalance Extremo):
   - Imprime en pantalla los 5 promedios cardinales de los sectores.
   - [CORRECCIÓN]: Si la diferencia directa entre la celda individual MÁXIMA y la celda 
     individual MÍNIMA (Brecha) de toda la matriz supera el 50.0%, activa una bandera 
     de emergencia: 'overload = 1'.
   - Reporte Final:
     Si 'overload == 1': Imprimir "¡BRECHA CRÍTICA! Desbalance térmico mayor al 50%. 
     Abriendo compuerta de la sección [Fila][Col] para contener a los Outriders a pie."
     Si 'overload == 0': Imprimir "Escudo resistiendo de forma constante. 
     Punto crítico en [Fila][Col], enviando a War Machine a reforzar."
*/

#include<iostream>
using namespace std;

int main(){
    
    // Declaración de matriz 
    float shield[3][5]={0};
    
    // Variables para nodos individuales (Brecha global)
    float nodo_max = -1.0, nodo_min = 101.0; 
    
    // Variables para análisis de sectores (Promedios de columnas)
    float min_prom_col = 101.0, max_prom_col = -1.0;
    float prom = 0, shield_prom = 0;
    
    int min_sec = 0, min_sec2 = 0, min_sec3 = 0, max_sec = 0, overload = 0, f = 0, c = 0;

    printf("ALERTA DEL SISTEMA, ESCUDOS CAYENDO!\n");

    // Llenado de datos y análisis de nodos individuales
    for(f=0; f<3; f++){
        for(c=0; c<5; c++){
            printf("Ingresar nivel de escudo (0 a 100%%) de seccion %d, %d: ", f+1, c+1);
            cin>>shield[f][c];

            if(shield[f][c]>100 || shield[f][c]<0){
                 printf("Error, valor no valido, intente de nuevo\n");
                 c--;
            }
            else{
                // Rastreo del nodo individual MÁS BAJO (La Brecha de Invasión)
                if(nodo_min > shield[f][c]){
                    nodo_min = shield[f][c];
                    min_sec3 = c; // Guarda la columna exacta del peligro
                    min_sec2 = f; // Guarda la fila exacta del peligro
                }
                // Rastreo del nodo individual MÁS ALTO
                if(nodo_max < shield[f][c]){
                    nodo_max = shield[f][c];
                }
            }
        }
    }

    // Analisis cardinal (Recorrido invertido por columnas)
    for(c=0; c<5; c++){
        for(f=0; f<3; f++){
            prom += shield[f][c];
        }

        prom/=3.0;
        switch (c)
        {
        case 0:
            printf("\nSector Norte, ");
            break;
        case 1:
            printf("\nSector Sur, ");
            break;
        case 2:
            printf("\nSector Este, ");
            break;
        case 3:
            printf("\nSector Oeste, ");
            break;
        default:
            printf("\nSector Central, ");
            break;
        }
        printf("promedio de escudo: %0.2f%%", prom);

        shield_prom += prom;

        // Buscamos el sector con menor promedio
        if(min_prom_col > prom){
            min_prom_col = prom;
            min_sec = c; 
        }
        
        // Buscamos el sector con mayor promedio
        if(max_prom_col < prom){
            max_prom_col = prom;
            max_sec = c; 
        }

        prom = 0;
    }

    printf("\n\nEl sector con menos energia promedio es: %d, con un promedio de: %0.2f%%", min_sec+1, min_prom_col);
    printf("\nEl sector con mas energia promedio es: %d, con un promedio de: %0.2f%%", max_sec+1, max_prom_col);

    // Criterio de Desbalance: Evaluamos la diferencia real entre los nodos extremos de la matriz
    if((nodo_max - nodo_min) > 50.0){
        overload = 1;
        printf("\n\nBRECHA CRITICA! Desbalance mayor al 50%% (Diferencia: %0.1f%%).", nodo_max - nodo_min);
        printf("\nAbriendo compuerta de la seccion %d, %d, WAKANDA FOREVER!.\n", min_sec2+1, min_sec3+1);
    } 
    else{
        overload = 0;
        printf("\n\nEscudo resistiendo de forma constante (Diferencia: %0.1f%%).", nodo_max - nodo_min);
        printf("\nPunto critico en %d,%d, enviando a War Machine a reforzar.\n", min_sec2+1, min_sec3+1);
    }

    shield_prom/=5.0;
    printf("\nEstado general del escudo, operando al %0.2f porciento de su capacidad.\n", shield_prom);
    
    return 0;
}